

name: Flutter Action

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
       flutter-version: '3.7.12'

    - run: flutter pub get
    - run: flutter build ios --debug --no-codesign

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Runner.app
        path: build/ios/iphoneos/*.app