

name: Flutter Action

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
       flutter-version: '3.7.12'

    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    
